import '../styles/globals.css';
import type { Metadata } from 'next';
import AntdProvider from '../providers/AntdProvider';
import StoreProvider from '../providers/StoreProvider';
// import { Geist, Geist_Mono } from 'next/font/google';
import ReactQueryProviders from '@/providers/reactQuery/ReactQueryProvider';
import SessionProviderWrapper from '@/providers/SessionProviderWrapper';

// const geistSans = Geist({
// 	variable: '--font-geist-sans',
// 	subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
// 	variable: '--font-geist-mono',
// 	subsets: ['latin'],
// });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fa" dir="rtl">
			<body className={`antialiased`}>
				<SessionProviderWrapper>
					<StoreProvider>
						<ReactQueryProviders>
							<AntdProvider>{children}</AntdProvider>
						</ReactQueryProviders>
					</StoreProvider>
				</SessionProviderWrapper>
			</body>
		</html>
	);
}
