import '../styles/globals.css';
import type { Metadata } from 'next';
import AntdProvider from '../providers/AntdProvider';
import StoreProvider from '../providers/StoreProvider';
// import { Geist, Geist_Mono } from 'next/font/google';
import ReactQueryProviders from '@/providers/reactQuery/ReactQueryProvider';
import AxiosProvider from '@/providers/AxiosProvider';

// const geistSans = Geist({
// 	variable: '--font-geist-sans',
// 	subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
// 	variable: '--font-geist-mono',
// 	subsets: ['latin'],
// });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fa" dir="rtl">
			<head>
				<script
				// dangerouslySetInnerHTML={{
				// 	__html: `
				//    (function(){
				//    try {
				//       var t = localStorage.getItem('theme');
				//       if (t === 'dark') {
				//          document.documentElement.classList.add('dark');
				//       } else {
				//          document.documentElement.classList.remove('dark');
				//       }
				//    } catch(e) {}
				//    })();
				//             `,
				// }}
				/>
			</head>
			<body className={`antialiased theme-root`}>
				{/* <SessionProviderWrapper> */}
				<StoreProvider>
					<AxiosProvider>
						<AntdProvider>
							<ReactQueryProviders>{children}</ReactQueryProviders>
						</AntdProvider>
					</AxiosProvider>
				</StoreProvider>
				{/* </SessionProviderWrapper> */}
			</body>
		</html>
	);
}
