import './globals.css';
import type { Metadata } from 'next';
import StoreProvider from './StoreProvider';
import { Geist, Geist_Mono } from 'next/font/google';
// import { AntdRegistry } from '@ant-design/nextjs-registry';
import AntdProvider from '@/providers/AntdProvider';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<StoreProvider>
					<AntdProvider>{children}</AntdProvider>
				</StoreProvider>
			</body>
		</html>
	);
}
